version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: solopilot-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - solopilot-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: solopilot-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: solopilot_user_service
    ports:
      - "5433:5432"
    volumes:
      - solopilot_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d solopilot_user_service"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - rabbitmq
    networks:
      - solopilot-network
    restart: unless-stopped

  user-service:
    build:
      context: ../../     # sends entire solopilot/ folder to Docker
      dockerfile: user-service/docker/Dockerfile
    image: solopilot/user-service:latest
    container_name: solopilot-user-service
    ports:
      - "8082:8080"
    env_file:
      - ../../.env-docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - solopilot-network
    restart: unless-stopped

  worker-service:
    build:
      context: ../../     # sends entire solopilot/ folder to Docker
      dockerfile: worker-service/docker/Dockerfile
    image: solopilot/worker-service:latest
    container_name: solopilot-worker-service
    ports:
      - "8083:8081"
    env_file:
      - ../../.env-docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      user-service:
        condition: service_healthy
    networks:
      - solopilot-network
    restart: unless-stopped

  frontend:
    build:
      context:  ../../solopilot-frontend               # same root as backends
      dockerfile: docker/Dockerfile
    image: solopilot/frontend:latest
    container_name: solopilot-frontend
    ports:
      - "5173:5173"                  # host:container
    depends_on:
      user-service:
        condition: service_healthy
    networks:
      - solopilot-network
    restart: unless-stopped

networks:
  solopilot-network:
    driver: bridge

volumes:
  solopilot_postgres_data:
